### PR TITLE
Selection parameter updated

### PR DESCRIPTION
**Pull request by djes**

### CODE REVIEW

**Review by natalyareznik-tomtom — APPROVED** [review]

**Comment by natalyareznik-tomtom** [comment]
Hi @djes, can you please merge your change? We are trying to use this plugin and have to maintain the code locally to be able to do so. It would be great if we could just used the latest binary.

**Review by nelson-mig-l — APPROVED** [review]

**Comment by nelson-mig-l** [comment]
Confirmed that solves the issue.

**Review by djes — COMMENTED** [review]
Fix small bug

**Comment by natalyareznik-tomtom** [comment]
@felferrari Can you please merge?

**Comment by felferrari** [comment]
Merged

**Comment by natalyareznik-tomtom** [comment]
@felferrari Thanks. Are you also going to release/publish a new version?

**Pull request merged**
